### ISSUE TITLE
What's the best way to integrate this patch into an existing react-native app? 

### ISSUE THREAD

**Issue by maxmandia** [mikehardy/rnfbdemo#12]
Hi, I'm very new to react native as well as rnf and wanted to know: what's the best way to integrate this patch into an existing react-native app? I was having so much trouble getting this to work with real devices and finally came across this patch. 

Any tips would be appreciated!

**Comment by mikehardy** [comment]
If you are talking about the `patches/react-native-0.69.0.patch` file, that is no longer needed in 0.69.1, but:

I always use https://github.com/ds300/patch-package/ to do things like this

If you are not talking about that, then I'm not sure, it depends on what you need to patch up. You can use ruby and Podfile tricks to patch up random objective-c things like I did in https://github.com/facebook/react-native/issues/31941#issuecomment-904995765

You can directly use `sed` in a script like I do in this make-demo.sh script here a lot.

Depends on your goal
