### ISSUE TITLE
Should the Android-statement be outside the iOS section?

### ISSUE THREAD

**Issue by Bilal-Abdeen** [mikehardy/rnfbdemo#9]
I wonder if the following statement should be moved after the "fi" statement.
```
  # workaround for poorly setup Android SDK environments
  USER=$(whoami)
  echo "sdk.dir=/Users/$USER/Library/Android/sdk" > android/local.properties
fi
```

**Comment by mikehardy** [comment]
Nope - that one is on purpose inside the Darwin check, this particular environment mis-configuration happens only on macOS in my experience, and that path is Darwin-specific.
